{% set name = "fantomas" %}
{% set version = "6.3.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fsprojects/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a825f4135ec8b68f3b6df3106bead149cd8f1ce9ce5e1f509b7deb64941cc1c7

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - fantomas --help

about:
  home: https://fsprojects.github.io/fantomas
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - license-files/
  summary: FSharp source code formatter
  dev_url: https://github.com/fsprojects/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
