{% set name = "fantomas" %}
{% set version = "6.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/fsprojects/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c4304d8b7c91f443760be82215d8753860cf0d9a42bc5a3adcb147f9314fc2cf

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - fantomas --help

about:
  home: https://fsprojects.github.io/fantomas
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - license-files/
  summary: FSharp source code formatter
  dev_url: https://github.com/fsprojects/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
