context:
  version: "8.0.0"

package:
  name: fantomas
  version: ${{ version }}

source:
  url: https://github.com/fsprojects/fantomas/archive/v${{ version }}.tar.gz
  sha256: 8f6ee0d0aa5de6daa4a2aa8137920dbc77606f2e8826a65c920ff715b61002fd

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet =8
    - nuget-license <3.1
  run:
    - dotnet =8

tests:
  - script:
      - fantomas --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - license-files/
  summary: FSharp source code formatter
  homepage: https://fsprojects.github.io/fantomas
  repository: https://github.com/fsprojects/fantomas

extra:
  recipe-maintainers:
    - danielnachun
