context:
  version: "7.0.2"

package:
  name: fantomas
  version: ${{ version }}

source:
  url: https://github.com/fsprojects/fantomas/archive/v${{ version }}.tar.gz
  sha256: 25c371988150995ef0063bbfd7b297c41e624edbf99cd7f109ceabc3395d628c

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - fantomas --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - license-files/
  summary: FSharp source code formatter
  homepage: https://fsprojects.github.io/fantomas
  repository: https://github.com/fsprojects/fantomas

extra:
  recipe-maintainers:
    - danielnachun
