context:
  version: "8.0.1"

package:
  name: fantomas
  version: ${{ version }}

source:
  url: https://github.com/fsprojects/fantomas/archive/v${{ version }}.tar.gz
  sha256: 7bd5654272c26e784665b6cd429b1c8d903d99d66538cea051f0a8ecd2b3c114

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet =8
    - nuget-license <3.1
  run:
    - dotnet =8

tests:
  - script:
      - fantomas --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - license-files/
  summary: FSharp source code formatter
  homepage: https://fsprojects.github.io/fantomas
  repository: https://github.com/fsprojects/fantomas

extra:
  recipe-maintainers:
    - danielnachun
